# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Cambio a imaen erroenea" # Es como un mensaje de commit para especificar porque se da el cambio
  name:  deployment-test
  labels:
    app:  deploymentfront
# Esto es el REPLICA SET
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxpod
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  #  type: RollingUpdate

  # Esto es el POD
  template:
    metadata:
      labels:
        app: nginxpod

  # Esto es o son los CONTAINERS
    spec:
      containers:
      - name:  nginxcontainer
        image: nginx:alpine
        ports:
          - containerPort: 190
