# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev
- master

stages:
  - stage: docker
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Build
        steps:
          - bash: echo $(DOCKER_USER)
            displayName: "Docker login"
  
  - stage: deploy
    dependsOn: docker
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Deploy
        steps:
          - bash: ls 
