# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  displayName: 'Go build'
  inputs:
    command: 'build'
    arguments: '-v -o mainApp main.go'
    workingDirectory: '$(System.DefaultWorkingDirectory)/applicationExample/backend/src'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/applicationExample/backend/src/mainApp'
    artifactName: 'drop'
