# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-backend-k8s-hands-on
  labels:
    app:  deployment-backend-k8s-hands-on
# Esto es el REPLICA SET
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-k8s-hands-on
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  #  type: RollingUpdate

  # Esto es el POD
  template:
    metadata:
      labels:
        app: backend-k8s-hands-on

  # Esto es o son los CONTAINERS
    spec:
      containers:
      - name:  container-k8s-hands-on
        image: k8s-hands-on-example:v2
        imagePullPolicy: IfNotPresent

---

# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: service-backend-k8s-hands-on
  namespace: default
  labels:
    app: service-backend-k8s-hands-on
spec:
  selector:
    app: backend-k8s-hands-on # Selector para los pods
  #type: NodePort
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
      #-------------Clusteip---------------------
      # use kubectl port-forward  services/service-backend-k8s-hands-on 7001:8080 (clusterip)
      # tambien desde k9s se puede crear un portforwarding pero directamente con el puerto del contenedor 9090

      #---------------Nodeport----------------------
      #dependiendo del puerto que nos asigna accedemos desde localhost:32072 ejemplo