name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: echo $DOCKER_TOKEN  | docker login -u $DOCKER_USER --password-stdin
    
    - name: Build the Docker backend image
      working-directory: applicationExample/backend
      run: docker build . --file Dockerfile --tag k8s-hands-on-example:latest
      #run: docker build . --file Dockerfile --tag k8s-hands-on-example:$(date +%s)
      
    - name: Build the Docker frontend image
      working-directory: applicationExample/frontend
      run: docker build . --file Dockerfile --tag frontend-k8s-hands-on:latest
      
    - name: Push docker images
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run : |
        docker tag k8s-hands-on-example:latest $DOCKER_USER/k8s-hands-on-example:latest
        docker tag frontend-k8s-hands-on:latest $DOCKER_USER/frontend-k8s-hands-on:latest
        docker push $DOCKER_USER/k8s-hands-on-example:latest
        docker push $DOCKER_USER/frontend-k8s-hands-on:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        docker pull $DOCKER_USER/k8s-hands-on-example:latest
        docker pull $DOCKER_USER/frontend-k8s-hands-on:latest

    - name: 'Run image'
      run : ls
      #env:
      #  DOCKER_USER: ${{ secrets.DOCKER_USER }}
      #run : docker run --rm $DOCKER_USER/k8s-hands-on-example:latest
      #id: deploy-to-webapp 
      #uses: azure/webapps-deploy@v2
      #with:
      #  app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 
        
  
