name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker backend image
      working-directory: applicationExample/backend
      run: docker build . --file Dockerfile --tag k8s-hands-on-example:$(date +%s)
    - name: Build the Docker frontend image
      working-directory: applicationExample/frontend
      run: docker build . --file Dockerfile --tag frontend-k8s-hands-on:$(date +%s)
