name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build
      working-directory: applicationExample/backend/src
      run: |
        go build -v -o mainApp main.go
        ls

    - name: Test
      working-directory: applicationExample/backend/src
      run: go test -v main.go
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: applicationExample/backend/src
    
