name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build
      working-directory: applicationExample/backend/src
      run: go build -v -o mainApp main.go
      
    - name: ls
      working-directory: applicationExample/backend/src
      run: ls

    #- name: Test
    #  run: go test -v ./...
