name: Go CI CD

on:
  push:
    branches: [ master , dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build
      working-directory: applicationExample/backend/src
      run: |
        go build -v -o mainApp main.go
        ls

    - name: Test
      working-directory: applicationExample/backend/src
      run: go test -v main.go
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: applicationExample/backend/src/mainApp
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: assets-for-download

    - name: 'Deploy to Azure WebApp'
      run : ls
      #id: deploy-to-webapp 
      #uses: azure/webapps-deploy@v2
      #with:
      #  app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
  deployProduction:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: assets-for-download

    - name: 'Deploy to Azure WebApp'
      run : ls
      #id: deploy-to-webapp 
      #uses: azure/webapps-deploy@v2
      #with:
      #  app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    
